esphome:
    name: esp32_knxrf_1
    platform: ESP32
    board: nodemcu-32s
  #  arduino_version: 1.0.4
    includes:
    - knx_rf.h
    - Crc16.h
    libraries:
    - "SmartRC-CC1101-Driver-Lib"
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:
  level: DEBUG
substitutions:
  hostname: "esp32_knxrf_1"

# Enable Home Assistant API
api:
   password: !secret api_password

ota:
   password: !secret ota_password

  
sensor:
- platform: custom
  lambda: |-
    std::map<std::string, UponorThermostat*> sensors;
    auto sensor1 = new UponorThermostat("0074040D58B","Master bed room");
    sensors[sensor1->id_] = sensor1;

    
    auto my_sensor = new KNXRFGateway(sensors);
    App.register_component(my_sensor);
    return {sensor1->current_temperature_sensor,sensor1->target_temperature_sensor,sensor1->battery_state_sensor,sensor1->rssi_sensor,sensor1->lqi_sensor};
  sensors:
    - name: "Master bedroom temperature"
      unit_of_measurement: °C
      accuracy_decimals: 2
      icon: "mdi:thermometer"
    - name: "Master bedroom target temperature"
      unit_of_measurement: °C
      accuracy_decimals: 1
      icon: "mdi:thermometer"
    - name: "Master bedroom thermostat battery state"
      icon: "mdi:battery"
      unit_of_measurement: "%"
      accuracy_decimals: 0
    - name: "Master bedroom thermostat rssi level db"
      icon: "mdi:wifi"
      accuracy_decimals: 0
    - name: "Master bedroom thermostat link quality"
      icon: "mdi:wifi"
      accuracy_decimals: 0
                    #icon: "${vars[0] >= 100 ? 'mdi:wifi' : vars[0] >= 80 ? 'mdi:wifi-strength-3' : vars[0] >= 60 ? 'mdi:wifi-strength-2' : 'mdi:wifi-strength-1' }"
    - name: "Office temperature"
      unit_of_measurement: °C
      accuracy_decimals: 2
      icon: "mdi:thermometer"
    - name: "Office target temperature"
      unit_of_measurement: °C
      accuracy_decimals: 1
      icon: "mdi:thermometer"
    - name: "Office thermostat battery state"
      icon: "mdi:battery"
      unit_of_measurement: "%"
      accuracy_decimals: 0
    - name: "Office thermostat rssi level db"
      icon: "mdi:wifi"
      accuracy_decimals: 0
    - name: "Office thermostat link quality"
      icon: "mdi:wifi"
      accuracy_decimals: 0

    - name: "Downstairs corridor temperature"
      unit_of_measurement: °C
      accuracy_decimals: 2
      icon: "mdi:thermometer"
    - name: "Downstairs corridor target temperature"
      unit_of_measurement: °C
      accuracy_decimals: 1
      icon: "mdi:thermometer"
    - name: "Downstairs corridor thermostat battery state"
      icon: "mdi:battery"
      unit_of_measurement: "%"
      accuracy_decimals: 0
    - name: "Downstairs corridorthermostat rssi level db"
      icon: "mdi:wifi"
      accuracy_decimals: 0
    - name: "Downstairs corridor thermostat link quality"
      icon: "mdi:wifi"
      accuracy_decimals: 0
    
    - name: "Service room temperature"
      unit_of_measurement: °C
      accuracy_decimals: 2
      icon: "mdi:thermometer"
    - name: "Service room target temperature"
      unit_of_measurement: °C
      accuracy_decimals: 1
      icon: "mdi:thermometer"
    - name: "Service room thermostat battery state"
      icon: "mdi:battery"
      unit_of_measurement: "%"
      accuracy_decimals: 0
    - name: "Service room thermostat rssi level db"
      icon: "mdi:wifi"
      accuracy_decimals: 0
    - name: "Service room thermostat link quality"
      icon: "mdi:wifi"
      accuracy_decimals: 0
  
    - name: "Movie room temperature"
      unit_of_measurement: °C
      accuracy_decimals: 2
      icon: "mdi:thermometer"
    - name: "Movie room target temperature"
      unit_of_measurement: °C
      accuracy_decimals: 1
      icon: "mdi:thermometer"
    - name: "Movie room thermostat battery state"
      icon: "mdi:battery"
      unit_of_measurement: "%"
      accuracy_decimals: 0
    - name: "Movie room thermostat rssi level db"
      icon: "mdi:wifi"
      accuracy_decimals: 0
    - name: "Movie room thermostat link quality"
      icon: "mdi:wifi"
      accuracy_decimals: 0

    - name: "Bar room temperature"
      unit_of_measurement: °C
      accuracy_decimals: 2
      icon: "mdi:thermometer"
    - name: "Bar room target temperature"
      unit_of_measurement: °C
      accuracy_decimals: 1
      icon: "mdi:thermometer"
    - name: "Bar room thermostat battery state"
      icon: "mdi:battery"
      unit_of_measurement: "%"
      accuracy_decimals: 0
    - name: "Bar room thermostat rssi level db"
      icon: "mdi:wifi"
      accuracy_decimals: 0
    - name: "Bar room thermostat link quality"
      icon: "mdi:wifi"
      accuracy_decimals: 0

    - name: "Living room temperature"
      unit_of_measurement: °C
      accuracy_decimals: 2
      icon: "mdi:thermometer"
    - name: "Living room target temperature"
      unit_of_measurement: °C
      accuracy_decimals: 1
      icon: "mdi:thermometer"
    - name: "Living room thermostat battery state"
      icon: "mdi:battery"
      unit_of_measurement: "%"
      accuracy_decimals: 0
    - name: "Living room thermostat rssi level db"
      icon: "mdi:wifi"
      accuracy_decimals: 0
    - name: "Living room thermostat link quality"
      icon: "mdi:wifi"
      accuracy_decimals: 0

    - name: "Kitchen temperature"
      unit_of_measurement: °C
      accuracy_decimals: 2
      icon: "mdi:thermometer"
    - name: "Kitchen target temperature"
      unit_of_measurement: °C
      accuracy_decimals: 1
      icon: "mdi:thermometer"
    - name: "Kitchen thermostat battery state"
      icon: "mdi:battery"
      unit_of_measurement: "%"
      accuracy_decimals: 0
    - name: "Kitchen thermostat rssi level db"
      icon: "mdi:wifi"
      accuracy_decimals: 0
    - name: "Kitchen thermostat link quality"
      icon: "mdi:wifi"
      accuracy_decimals: 0
    

    - name: "Dining room temperature"
      unit_of_measurement: °C
      accuracy_decimals: 2
      icon: "mdi:thermometer"
    - name: "Dining room target temperature"
      unit_of_measurement: °C
      accuracy_decimals: 1
      icon: "mdi:thermometer"
    - name: "Dining room thermostat battery state"
      icon: "mdi:battery"
      unit_of_measurement: "%"
      accuracy_decimals: 0
    - name: "Dining room thermostat rssi level db"
      icon: "mdi:wifi"
      accuracy_decimals: 0
    - name: "Dining room thermostat link quality"
      icon: "mdi:wifi"
      accuracy_decimals: 0


    - name: "Bedroom 1 temperature"
      unit_of_measurement: °C
      accuracy_decimals: 2
      icon: "mdi:thermometer"
    - name: "Bedroom 1 target temperature"
      unit_of_measurement: °C
      accuracy_decimals: 1
      icon: "mdi:thermometer"
    - name: "Bedroom 1 thermostat battery state"
      icon: "mdi:battery"
      unit_of_measurement: "%"
      accuracy_decimals: 0
    - name: "Bedroom 1 thermostat rssi level db"
      icon: "mdi:wifi"
      accuracy_decimals: 0
    - name: "Bedroom 1 thermostat link quality"
      icon: "mdi:wifi"
      accuracy_decimals: 0

    - name: "Upstairs corridor temperature"
      unit_of_measurement: °C
      accuracy_decimals: 2
      icon: "mdi:thermometer"
    - name: "Upstairs corridor target temperature"
      unit_of_measurement: °C
      accuracy_decimals: 1
      icon: "mdi:thermometer"
    - name: "Upstairs corridor thermostat battery state"
      icon: "mdi:battery"
      unit_of_measurement: "%"
      accuracy_decimals: 0
    - name: "Upstairs corridor thermostat rssi level db"
      icon: "mdi:wifi"
      accuracy_decimals: 0
    - name: "Upstairs corridor thermostat link quality"
      icon: "mdi:wifi"
      accuracy_decimals: 0

    - name: "Bedroom 2 temperature"
      unit_of_measurement: °C
      accuracy_decimals: 2
      icon: "mdi:thermometer"
    - name: "Bedroom 2 target temperature"
      unit_of_measurement: °C
      accuracy_decimals: 1
      icon: "mdi:thermometer"
    - name: "Bedroom 2 thermostat battery state"
      icon: "mdi:battery"
      unit_of_measurement: "%"
      accuracy_decimals: 0
    - name: "Bedroom 2 thermostat rssi level db"
      icon: "mdi:wifi"
      accuracy_decimals: 0
    - name: "Bedroom 2 thermostat link quality"
      icon: "mdi:wifi"
      accuracy_decimals: 0

    - name: "Bedroom 3 temperature"
      unit_of_measurement: °C
      accuracy_decimals: 2
      icon: "mdi:thermometer"
    - name: "Bedroom 3 target temperature"
      unit_of_measurement: °C
      accuracy_decimals: 1
      icon: "mdi:thermometer"
    - name: "Bedroom 3 thermostat battery state"
      icon: "mdi:battery"
      unit_of_measurement: "%"
      accuracy_decimals: 0
    - name: "Bedroom 3 thermostat rssi level db"
      icon: "mdi:wifi"
      accuracy_decimals: 0
    - name: "Bedroom 3 thermostat link quality"
      icon: "mdi:wifi"
      accuracy_decimals: 0
