esphome:
  name: knxrf
  platform: esp32
  board: nodemcu-32s
  includes:
  - knx_rf.h
  - Crc16.h
  libraries:
  - "SPI"
  - "SmartRC-CC1101-Driver-Lib"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:

api:

ota:
   password: !secret ota_password

sensor:
- platform: custom
  lambda: |-
    auto KNXRF = new KNXRFGateway("007400002C2C","007400002C2F","007400002C26","0074000078E1","0074000078F9","0074000078E4","007400002C29","0074000034F8");
    App.register_component(KNXRF);
    return {KNXRF->temperature1, KNXRF->temperature2, KNXRF->temperature3, KNXRF->temperature4, KNXRF->temperature5, KNXRF->temperature6, KNXRF->temperature7, KNXRF->temperature8};

  sensors:
  - name: "Temperature1"
    unit_of_measurement: "°C"
    accuracy_decimals: 1
  - name: "Temperature2"
    unit_of_measurement: "°C"
    accuracy_decimals: 1
  - name: "Temperature3"
    unit_of_measurement: "°C"
    accuracy_decimals: 1
  - name: "Temperature4"
    unit_of_measurement: "°C"
    accuracy_decimals: 1
  - name: "Temperature5"
    unit_of_measurement: "°C"
    accuracy_decimals: 1
  - name: "Temperature6"
    unit_of_measurement: "°C"
    accuracy_decimals: 1
  - name: "Temperature7"
    unit_of_measurement: "°C"
    accuracy_decimals: 1
  - name: "Temperature8"
    unit_of_measurement: "°C"
    accuracy_decimals: 1
