esphome:
  name: knxrf

external_components:
  - source:
      type: local
      path: components

knxrfgateway:
  id: my_gateway
  sensors:
    - name: "Living room temperature"
      knx_id: "0011223344FF"

esp32:
  board: nodemcu-32s
  framework:
    type: arduino
    advanced:
      sram1_as_iram: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  level: DEBUG
  logs:
    knxrfgateway: DEBUG

api:
  encryption:
    key: !secret api_encryption_key_knxrf

ota:
  - platform: esphome
    password: !secret ota_password
